In [3]:
import numpy as np
mylist = [1,2,3,4]
myarray = np.array(mylist)
myarray

array([1, 2, 3, 4])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.random.rand(4,5)
np.random.randn(2,2)


array([3, 6, 9, 2, 8, 8, 7, 9])

In [25]:
np.random.randint(2,10,4).reshape(2,2)


array([[8, 8],
       [4, 3]])

In [27]:
np.random.randint(2,10,4).min()

4

In [29]:
np.random.randint(2,10,4).max()

9

In [31]:
np.random.randint(2,10,4).shape

(4,)

In [32]:
np.random.randint(2,10,4).dtype

dtype('int32')

In [33]:
my_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
my_2d[0,0]

1

In [4]:
my_3d = np.arange(0,50).reshape(5,10)

In [49]:
my_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [5]:
my_3d[1:,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [52]:
my_3d[:] = 5
my_3d

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [6]:
my_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [9]:
my_3d > 15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [12]:
my_3d[my_3d>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
myarr = np.random.rand(10)

In [20]:
myarr = myarr.reshape(2,5)

In [21]:
myarr

array([[0.64003801, 0.54558249, 0.43342694, 0.5836483 , 0.15668679],
       [0.4265581 , 0.50679682, 0.87846451, 0.72207514, 0.35249696]])

In [25]:
myarr[myarr > 0.5]

array([0.64003801, 0.54558249, 0.5836483 , 0.50679682, 0.87846451,
       0.72207514])